### PR TITLE
Add FunctionalAligner

### PR DESCRIPTION
**Pull request by angelosilvestre**
Add FunctionalAligner

This PR introduces `FunctionalAligner` , which is a `FollowerAligner` that delegates to a callback.

### CODE REVIEW

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
@angelosilvestre do you know what's going on with the goldens?

**Comment by angelosilvestre** [comment]
@matthew-carroll It seems that, with Material 3, the default background color changed, causing the tests to fail.

I updated the goldens.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Pull request merged**
